### PR TITLE
70 contributing md

### PR DESCRIPTION
**Pull request by francisluong**
To address issue #70, add a stripped down document on contributing.

### CODE REVIEW

**Comment by francisluong** [comment]
Can I get a volunteer for review?  @mikemackintosh @gauthier-delacroix @bluemonk 

Thanks!

**Comment by gauthier-delacroix** [comment]
Seems pretty clear. Just, why don't you add this to the readme ?
Many projects have a contribution section in the readme. Not sure I'd have the reflex to look for a contribution MD...
And what's this `.idea/` ignore ? Not sure you should gitignore every personal working directory contributors could use...

**Comment by mikemackintosh** [comment]
Looks great, but I think adding this to the README directly gives better attribution than having a contributors file.

**Comment by francisluong** [comment]
Main benefit is that Github does a banner for CONTRIBUTING.md:
https://github.com/blog/1184-contributing-guidelines

Lemme resolve conflicts and I will merge.

@gauthier-delacroix: .idea/ is a meta folder used by IntelliJ/Rubymine to store config state specific to that edittor/IDE.  It will be common for anyone who uses it.

**Comment by francisluong** [comment]
If all looks well to you guys, can one of you merge?  It's tradition on the coding teams I work on that we do not merge our own PRs.
@gauthier-delacroix @mikemackintosh

**Comment by mikemackintosh** [comment]
Checking it out now

**Comment by mikemackintosh** [comment]
Nice catch on the `CONTRIBUTING.md` banner. Looks good. Merging.

**Comment by francisluong** [comment]
Sweet.  Next... to get bluemonk to move this repo to an org and we can get Travis CI setup without requiring his direct involvement.

**Comment by gauthier-delacroix** [comment]
> Main benefit is that Github does a banner for CONTRIBUTING.md:
> https://github.com/blog/1184-contributing-guidelines
> 
> @gauthier-delacroix: .idea/ is a meta folder used by IntelliJ/Rubymine to store config state specific to that edittor/IDE. It will be common for anyone who uses it.
> 
Learnt 2 things today ;o)

**Pull request merged**
