### PR TITLE
Added ranges support

### PR DESCRIPTION
**Pull request by t3hk0d3**
Follow #26

### CODE REVIEW

**Comment by t3hk0d3** [comment]
oh wow. Most laziest gem owner evar.

**Comment by zaargy** [comment]
+1 this looks like a useful feature. Please merge.

**Comment by mikemackintosh** [comment]
I definitely see benefit in using this. I think it's a feature that helps provide consistency and stability for a 1.0 release. The only downside with this PR is that it is IPv4 only. Would you like to take a stab at adding support for IPv6?

**Comment by t3hk0d3** [comment]
@mikemackintosh Basically you just need to add ``#to_int`` method, and Ruby will do everything else for you.

**Comment by t3hk0d3** [comment]
@mikemackintosh Rebased and added IPv6 support.

**Comment by mikemackintosh** [comment]
thanks

**Comment by shtirlic** [comment]
+1 to this

**Comment by t3hk0d3** [comment]
Squashed into single commit and rebased on current master.

**Comment by t3hk0d3** [comment]
@mikemackintosh Any problems with this PR?

**Comment by mikemackintosh** [comment]
I will get this included in the next pull-feature set.

**Comment by t3hk0d3** [comment]
dang it. switched to ``IPAddr`` in stdlib in all projects. Can't really afford to have github links in Gemfiles.

**Pull request closed without merging**
